services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depend_on:
      - redis
      - rabbitmq
  
  frontend:
    build:
    context: ./frontend
    dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depend_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
