name: backend-cicd

on:
  push:
    branches: ["dev"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["dev"]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 and cache Maven dependencies
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and Test with Maven
        run: |
          cd backend
          mvn -B clean verify -Dspring.profiles.active=test

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: backend/target/surefire-reports
