name: Backend CI
on:
  workflow_call:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    env:
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      SPRING_PROFILES_ACTIVE: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin

      - name: Build backend
        run: |
          cd backend
          ./mvnw clean install -DskipTests=false

      - name: Run backend tests
        run: |
          cd backend
          ./mvnw test
