name: Full-Stack Integration CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker (optional, can skip if no registry)
        run: echo "No Docker registry needed for local CI"

      - name: Build and run full stack with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build
          # Wait for services to be ready
          echo "Waiting 30s for services..."
          sleep 30

      - name: Run backend tests
        run: |
          docker-compose exec -T backend ./mvnw test

      - name: Run AI worker tests
        run: |
          docker-compose exec -T ai-service python -m unittest discover -s tests

      - name: Run frontend tests
        run: |
          docker-compose exec -T frontend npm test

      - name: Tear down stack
        run: |
          docker-compose down -v
